// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcfvuslwctqigehkagze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnZ1c2x3Y3RxaWdlaGthZ3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMzQzNzksImV4cCI6MjA1NDcxMDM3OX0.7cxkGSL877meF84sYohCgZVjwdT64osbCfpS6pe0gOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);